### ISSUE TITLE
Support files larger than 1GB (32bit) and 2GB (64bit)

### ISSUE THREAD

**Issue by Th3Van** [orcproject/orc#19]
### Package Version

Replace the value below using the output from `orc --version`.

```
orc      0.0.0
protocol 2.0.0
```

Replace the value below using the output from `node --version`.

```
v6.11.0
```

### Actual Behavior

Trying to download 1GB file ( just uploaded 40 min ago), but fails :
```
root@server007:~/orc# curl http://127.0.0.1:4445/28625e89-72ca-46a3-9ccb-5e5a57b7aeb1 > 1g-file-download.test                                      
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:13:22 --:--:--     0
curl: (52) Empty reply from server

{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":17852,"level":30,"msg":"received response from 8146be4634305df3ac00d8da967fd368c9e1ad37 to 2d78723e-62c0-49d7-b624-70600c995451","time":"2017-07-14T23:09:10.124Z","v":0}
{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":17852,"level":30,"msg":"received response from 90d000381ffdc2c5fb8c7d202571ca04745810fe to eda89ed1-e186-4660-80f2-5482c941efd3","time":"2017-07-14T23:09:10.858Z","v":0}
{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":17852,"level":30,"msg":"received response from 992070d382218b400fcd9e99e00538d0d67b7c45 to f4ea15cd-1ac6-4b7c-8ab1-64da8ef06c4d","time":"2017-07-14T23:09:10.861Z","v":0}
{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":17852,"level":30,"msg":"received PUBLISH (916a74d4-7cf5-4711-8adc-8dc1300f2033) from f349d52e5028b58318c2db176e2351fd6981a56a (https://xm4jwtfe64ycojbh.onion:443)","time":"2017-07-14T23:09:11.529Z","v":0}
{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":17852,"level":30,"msg":"sending response to f349d52e5028b58318c2db176e2351fd6981a56a for 916a74d4-7cf5-4711-8adc-8dc1300f2033","time":"2017-07-14T23:09:11.534Z","v":0}
{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":17852,"level":40,"msg":"connection timed out","time":"2017-07-14T23:09:35.911Z","v":0}
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at Function.Buffer.concat (buffer.js:309:23)
    at Readable.downloadStream.on (/root/orc/lib/bridge.js:535:25)
    at emitNone (events.js:86:13)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. openssl rand 1000000000 > 1g-file.test  
2. curl -F "file=@1g-file.test;filename=1g-file.test" http://127.0.0.1:4445 | jq | grep '"id"'
3. curl http://127.0.0.1:4445/28625e89-72ca-46a3-9ccb-5e5a57b7aeb1 > 1g-file-download.tes

**Comment by bookchin** [comment]
Are you are a 32 or 64 bit architecture? https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_class_method_buffer_allocunsafe_size

**Comment by bookchin** [comment]
https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_buffer_kmaxlength

**Comment by bookchin** [comment]
Preventing upload of files too large for arch in https://github.com/orcproject/orc/commit/ccfc9401ba09d8f1a60375a33380074b5e91604f

Relabeling this as a feature now to support larger files.

**Comment by Th3Van** [comment]
```
root@server007:~# uname -a
Linux server007 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
root@server007:~# dpkg --print-architecture
amd64
```
