### ISSUE TITLE
Cannot read property 'kMaxLength' of null

### ISSUE THREAD

**Issue by Th3Van** [orcproject/orc#22]
### Package Version

Replace the value below using the output from `orc --version`.

```
orc      0.0.0
protocol 2.0.0
```

Replace the value below using the output from `node --version`.

```
v6.11.0
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in back ticks.

Uploading a 100MB file seems to be working flawlessly :
```
root@server007:~/orc# openssl rand 100000000 > 100MB-File.test
root@server007:~/orc# curl -F "file=@100MB-File.test;filename=100MB-File.test" http://127.0.0.1:4445 | jq | grep '"id"'                             
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.3M    0 20276  100 95.3M    137   662k  0:02:27  0:02:27 --:--:--     0
  "id": "d55e81af-66cc-4082-97fa-8d6af1145e9f",
```

Download :
```
root@server007:~/orc# curl http://127.0.0.1:4445/d55e81af-66cc-4082-97fa-8d6af1145e9f > 100MB-file-download.test
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 4445: Connection refused

{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":9453,"level":30,"msg":"received response from b95d3b65cee77810589fe21a542a5a206ad024e5 to 96db0d68-d538-45d3-af3e-58ddf36f1ad1","time":"2017-07-16T01:25:22.226Z","v":0}
{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":9453,"level":30,"msg":"received PUBLISH (3432e8cb-944b-47c7-b1aa-ec3af566da9c) from 5035d48be2a693225abb3bda61b06e98a68278da (https://jspzffdwyhzbsxgi.onion:443)","time":"2017-07-16T01:25:22.385Z","v":0}
{"name":"edbfeca1783946994c6b08479d48d0f6c27888a1","hostname":"server007","pid":9453,"level":30,"msg":"sending response to 5035d48be2a693225abb3bda61b06e98a68278da for 3432e8cb-944b-47c7-b1aa-ec3af566da9c","time":"2017-07-16T01:25:22.386Z","v":0}
/root/orc/lib/bridge.js:577
      if (size > buffer.kMaxLength) {
                       ^

TypeError: Cannot read property 'kMaxLength' of null
    at objects.get (/root/orc/lib/bridge.js:577:24)
    at /root/orc/node_modules/tiny/lib/tiny.js:1027:12
    at next (/root/orc/node_modules/tiny/lib/tiny.js:1704:14)
    at /root/orc/node_modules/tiny/lib/tiny.js:1014:16
    at /root/orc/node_modules/tiny/lib/tiny.js:737:12
    at /root/orc/node_modules/tiny/lib/tiny.js:718:12
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

**1.** openssl rand 100000000 > 100MB-File.test
**2.** curl -F "file=@100MB-File.test;filename=100MB-File.test" http://127.0.0.1:4445 | jq | grep '"id"'
**3.** curl http://127.0.0.1:4445/d55e81af-66cc-4082-97fa-8d6af1145e9f > 100MB-file-download.tes**t**

**Comment by bookchin** [comment]
Gah, thanks - name collision. Fixed https://github.com/orcproject/orc/commit/83f19675dfba7604e4d36cefa93926e382db3136

Time to get test coverage back up :)
