### ISSUE TITLE
Startup error on windows host

### ISSUE THREAD

**Issue by VoidStructure** [orcproject/orc#37]
### Package Version
```
orc      7.0.0-beta5
protocol 2.0.0
```
### Node Version

```
v6.11.1
```
### Host Info

```
OS: Windows 10 64 bit Build 15063
Docker: 17.06.0-ce-win19 (12801)
```

### Expected Behavior

After running the following command the docker volume starts up, creates a shared folder with the host machine and connects to the network.
`docker run -v /E/.config/orc:/root/.config/orc -t orcproject/orc:latest`

`/E/.config/orc` refers to `E:\.config\orc` on the host

### Actual Behavior

The docker volume starts up but crashes shortly after and produces following stack trace. 
```
{"name":"42c4cb5d9f5ddea4e64c5f535985c7330a7ef7f3","hostname":"ef71cc431d66","pid":12,"level":30,"msg":"establishing local bridge at 0.0.0.0:4445","time":"2017-07-29T20:13:05.456Z","v":0}
{"name":"42c4cb5d9f5ddea4e64c5f535985c7330a7ef7f3","hostname":"ef71cc431d66","pid":12,"level":30,"msg":"establishing public directory server at 0.0.0.0:4446","time":"2017-07-29T20:13:05.457Z","v":0}
{"name":"42c4cb5d9f5ddea4e64c5f535985c7330a7ef7f3","hostname":"ef71cc431d66","pid":12,"level":30,"msg":"bootstrapping tor and establishing hidden service","time":"2017-07-29T20:13:05.458Z","v":0}
{"name":"42c4cb5d9f5ddea4e64c5f535985c7330a7ef7f3","hostname":"ef71cc431d66","pid":12,"level":30,"msg":"spawning tor client and controller","time":"2017-07-29T20:13:05.458Z","v":0}
{"name":"42c4cb5d9f5ddea4e64c5f535985c7330a7ef7f3","hostname":"ef71cc431d66","pid":12,"level":30,"msg":"gui listening on 0.0.0.0:8080","time":"2017-07-29T20:13:05.473Z","v":0}
{"name":"42c4cb5d9f5ddea4e64c5f535985c7330a7ef7f3","hostname":"ef71cc431d66","pid":12,"level":30,"msg":"control server bound to 0.0.0.0:4444","time":"2017-07-29T20:13:05.474Z","v":0}

events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /root/.config/orc/contracts.db: Invalid argument
    at /root/orc/node_modules/levelup/lib/levelup.js:117:34
    at /root/orc/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

### Steps to Reproduce

1. `docker pull orcproject/orc`
2. `mkdir E:\.config\orc` or any other directory
3. `docker run -v /E/.config/orc:/root/.config/orc -t orcproject/orc:latest`

### Additional Information

```
docker run -v /E/.config/orc:/root/.config/orc -t orcproject/orc:latest ls -l /root/.config/orc
```
returns 

```
drwxr-xr-x 2 root root    0 Jul 29 20:13 __bridge.staging
-rwxr-xr-x 1 root root    0 Jul 29 20:13 capacity.cache
-rwxr-xr-x 1 root root  976 Jul 29 20:13 certificate.pem
-rwxr-xr-x 1 root root 2178 Jul 29 20:13 config
drwxr-xr-x 2 root root    0 Jul 29 20:13 contracts.db
drwxr-xr-x 2 root root    0 Jul 29 20:13 directory.db
-rwxr-xr-x 1 root root    0 Jul 29 20:13 objects.meta
-rwxr-xr-x 1 root root  890 Jul 29 20:13 onion_key
-rwxr-xr-x 1 root root 1678 Jul 29 20:13 service_key.pem
drwxr-xr-x 2 root root    0 Jul 29 20:13 shards
-rwxr-xr-x 1 root root  111 Jul 29 20:13 x_private_key
```

Similar issues:
https://github.com/Level/levelup/issues/222
https://github.com/Storj/storjshare-cli/issues/144

**Comment by bookchin** [comment]
#38
