### ISSUE TITLE
crash on audit

### ISSUE THREAD

**Issue by bookchin** [orcproject/orc#91]
```
buffer.js:768
        return this.hexWrite(string, offset, length);
                    ^

TypeError: Invalid hex string
    at Buffer.write (buffer.js:768:21)
    at fromString (buffer.js:212:18)
    at Function.Buffer.from (buffer.js:104:12)
    at node.auditRemoteShards (/home/bookchin/Code/orc/lib/bridge.js:976:20)
    at wrapped (/home/bookchin/Code/orc/node_modules/kad/lib/node-abstract.js:213:7)
    at Node._process (/home/bookchin/Code/orc/node_modules/kad/lib/node-abstract.js:154:5)
    at MetaPipe.rpc.deserializer.on (/home/bookchin/Code/orc/node_modules/kad/lib/node-abstract.js:93:34)
    at emitOne (events.js:96:13)
    at MetaPipe.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at MetaPipe.Readable.push (_stream_readable.js:136:10)
    at MetaPipe.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:77:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Transform.pipeline.(anonymous function).once (/home/bookchin/Code/orc/node_modules/metapipe/index.js:48:7)
    at Object.onceWrapper (events.js:293:19)
```

**Comment by bookchin** [comment]
This bug occurs when the `ObjectPointer#shards.audits.root` somehow gets stored with the incorrect encoding and upon the next AUDIT for this shard, converting the expected hex string to a buffer fails.
